apiVersion: v1
kind: Service
metadata:
  name: vg-service
  labels:
    app: vg-devops-project
spec:
  selector:
    app: vg-devops-project
  type: LoadBalancer
  ports:
    - port: 8080           # POD Level
      targetPort: 8080     # Cluster Level
      nodePort: 31200      # external level
